Repository stlink-org/stlink, pull requests merged in 2020-04, with the labels that each got.

#900 add usb pid for st-link v2.1, found on nucleo l432kc
  etc/udev/rules.d/49-stlinkv2-1.rules
  include/stlink/usb.h
  src/usb.c
Labels: code/feature-request, programmer/stlinkv2-1, status/resolved, target/stm32l4

#895 [compatibility] update of libusb
  CMakeLists.txt
  cmake/modules/FindLibUSB.cmake
  include/stlink/sg.h
  include/stlink/stlinkusb.h
  include/stlink/usb.h
  src/usb.c
Labels: code/compatibility, dependency/libusb, priority/high

#901 stm32g4 chips update
  src/chipid.c
Labels: code/feature-request, status/resolved, target/stm32g4

#910 stm32gx improvements
  include/stlink.h
  include/stlink/chipid.h
  src/chipid.c
  src/common.c
Labels: code/feature-request, code/feedback, status/resolved, target/stm32g0, target/stm32g4

#913 Fix dead loop after an unexpected unplug
  src/gdbserver/gdb-server.c
Labels: bug/fixed, component/libstlink, component/st-util, dependency/libusb, error/gdb-server, status/resolved

#918 Fixed st-info --probe mechanism
  include/stlink/usb.h
  src/usb.c
Labels: bug/fixed, component/st-info, programmer/stlinkv1, status/resolved, status/resolved-verified

#920 Fixed broken build on 32-bit systems
  src/common.c
  src/gdbserver/gdb-server.c
Labels: bug/compilation, bug/fixed, os/macOS, status/resolved

#921 Enhance error log with file path for map_file()
  src/common.c
Labels: code/feedback, status/resolved

#925 st-flash: minor usage fix, and make cmdline parsing more user friendly
  src/tools/flash.c
  src/tools/flash_opts.c
Labels: code/feedback, status/resolved

#924 Add md5 checksum for binary file
  CMakeLists.txt
  doc/tutorial.md
  src/common.c
  src/md5.c
  src/md5.h
Labels: code/feature-request, component/st-flash, general/documention, status/resolved

#922 flash.c: stlink_open_usb is actually able to open v1 and v2 (and v3)
  src/tools/flash.c
  src/tools/flash_opts.c
Labels: code/feedback, code/refactoring, component/st-flash, programmer/stlinkv1, programmer/stlinkv2, programmer/stlinkv3, status/resolved

#927 overall option code rework
  include/stlink.h
  include/stlink/chipid.h
  include/stm32.h
  src/chipid.c
  src/common.c
  src/tools/flash.c
Labels: code/feature-request, code/feedback, code/refactoring, component/st-flash, status/resolved

#935 Add CMAKEFLAGS and install target
  Makefile
Labels: code/feature-request, status/resolved

#929 Build settings
  .travis.sh
  .travis.yml
  CHANGELOG.md
  CMakeLists.txt
  LICENSE.md
  Makefile
  README.md
  cmake/c_flag_overrides.cmake
  cmake/modules/Find7zip.cmake
  cmake/modules/FindLibUSB.cmake
  cmake/modules/Findlibusb.cmake
  cmake/version.cmake
  debian/control
  debian/copyright
  debian/libstlink-dev.install
  debian/pkg-config/CMakeLists.txt
  debian/pkg-config/pkg-config.pc.cmake
  debian/watch
  doc/compiling.md
  doc/version_support.md
  include/stlink/tools/flash.h
  src/stlink-gui/CMakeLists.txt
  src/stlink-gui/gui.c
  src/stlink-gui/gui.h
  src/stlink-gui/gui.ui
  src/stlink-gui/icons/export-icons.sh
  src/stlink-gui/icons/hicolor/128x128/apps/stlink-gui.png
  src/stlink-gui/icons/hicolor/16x16/apps/stlink-gui.png
  src/stlink-gui/icons/hicolor/22x22/apps/stlink-gui.png
  src/stlink-gui/icons/hicolor/24x24/apps/stlink-gui.png
  src/stlink-gui/icons/hicolor/256x256/apps/stlink-gui.png
  src/stlink-gui/icons/hicolor/32x32/apps/stlink-gui.png
  src/stlink-gui/icons/hicolor/48x48/apps/stlink-gui.png
  src/stlink-gui/icons/hicolor/64x64/apps/stlink-gui.png
  src/stlink-gui/icons/stlink-gui.png
  src/stlink-gui/icons/stlink-gui.svg
  src/stlink-gui/icons/stlink-gui.xpm
  src/stlink-gui/icons/stlink-gui_48.png
  src/stlink-gui/stlink-gui.desktop
  src/tools/gui/CMakeLists.txt
  src/tools/gui/art/export-icons.sh
  tests/flash.c
  tests/sg.c
  tests/usb.c
Labels: code/feature-request, code/feedback, code/refactoring, component/gui-gtk3, os/freeBSD, os/linux, os/macOS, status/resolved

#938 Fix uninitialized cpuid
  src/common.c
  tests/usb.c
Labels: bug/compilation, bug/fixed, os/linux, status/resolved

#933 handle probed stlink with unconnected target properly
  src/gdbserver/gdb-server.c
  src/tools/flash.c
  src/usb.c
Labels: bug/fixed, code/feedback, code/refactoring, status/resolved

#943 handle probed stlink with unconnected target properly
  src/gdbserver/gdb-server.c
  src/tools/flash.c
  src/usb.c
Labels: bug/fixed, code/feedback, code/refactoring, component/st-info, status/resolved

#934 st-util: removed now useless v1/v2 STLink version stuff
  doc/man/st-flash.md
  doc/man/st-info.md
  doc/man/st-util.md
  doc/tutorial.md
  src/gdbserver/gdb-server.c
Labels: code/feedback, code/refactoring, general/documention, status/resolved

#941 [refactoring] Cleanup for option bytes and flash settings
  include/stlink.h
  src/chipid.c
  src/common.c
Labels: code/feature-request, code/feedback, code/refactoring, status/resolved

#942 Added compilation guideline for MSVC toolchain
  doc/compiling.md
Labels: general/documention, status/resolved

#945 Enhanced output for error msg "addr not a multiple of pagesize, not supported"
  src/common.c
Labels: code/feedback, component/st-flash, status/resolved, target/stm32f4

#947 [refactoring] Cleanup of cmake build process
  CMakeLists.txt
  LICENSE.md
  Makefile
  cmake/modules/Find7zip.cmake
  cmake/modules/Findlibusb.cmake
  cmake/packaging/CMakeLists.txt
  cmake/packaging/debian/copyright
  cmake/pkgconfig/CMakeLists.txt
  cmake/pkgconfig/pkgconfig.pc.cmake
  debian/pkg-config/CMakeLists.txt
  doc/compiling.md
  doc/man/CMakeLists.txt
  include/CMakeLists.txt
  include/stlink.h
  include/stlink/flash_loader.h
  include/stlink/tools/flash.h
  src/chipid.c
  src/common.c
  src/flash_loader.c
  src/gdbserver/CMakeLists.txt
  src/getopt/LICENSE.txt
  src/getopt/getopt.c
  src/libusb_settings.h
  src/logging.c
  src/logging.h
  src/md5.c
  src/mmap.c
  src/mmap.h
  src/sg.c
  src/sg.h
  src/st-util/gdb-remote.c
  src/st-util/gdb-remote.h
  src/st-util/gdb-server.c
  src/st-util/gdb-server.h
  src/st-util/semihosting.c
  src/st-util/semihosting.h
  src/stlink-gui/CMakeLists.txt
  src/stlink-gui/gui.c
  src/stlink-gui/stlink-gui.ui
  src/tools/flash.c
  src/tools/flash_opts.c
  src/usb.c
  src/usb.h
  tests/CMakeLists.txt
  tests/flash.c
  tests/sg.c
  tests/usb.c
Labels: code/feedback, code/refactoring, component/gui-gtk3, component/libstlink, component/st-flash, component/st-info, component/st-util, os/linux, os/macOS, os/windows, status/resolved
