Repository stlink-org/stlink, pull requests merged in 2020-03, with the labels that each got.

#870 add win32 travis build
  .travis-lin-mingw.sh
  .travis.yml
  cmake/modules/FindLibUSB.cmake
  src/usb.c
Labels: code/feature-request, os/windows

#857 Improved support for STM32G0xx series parts to fix Issue #850
  include/stlink/chipid.h
  src/chipid.c
Labels: code/feature-request, target/stm32g0

#847 Support for STM32L4, SM32L1 option bytes write.
  src/common.c
Labels: code/feature-request, target/stm32l1, target/stm32l4

#882 Fixed wait-loop for flash_loader_run() & F72/F73 device description
  src/chipid.c
  src/flash_loader.c
Labels: bug/fixed, code/feedback, error/flash-loader, status/resolved

#883 Added more error info to WLOGs during probe.
  src/usb.c
Labels: code/feature-request, code/feedback, status/resolved

#885 check if app's need for libssp.
  CMakeLists.txt
  src/gdbserver/CMakeLists.txt
  src/tools/gui/CMakeLists.txt
  tests/CMakeLists.txt
Labels: code/feedback, error/compilation, status/resolved

#890 Error return in failed probe (Fixes #887)
  src/usb.c
Labels: bug/fixed, dependency/libusb, status/resolved

#886 Silence unnecessary messages (Fixes #240)
  src/chipid.c
  src/common.c
  src/gdbserver/gdb-server.c
  src/usb.c
Labels: code/feedback, status/resolved

#894 setting up a libusb log level accordingly to verbosity.
  include/stlink.h
  include/stlink/logging.h
  src/logging.c
  src/sg.c
  src/usb.c
Labels: code/feature-request, dependency/libusb
