Repository stlink-org/stlink, pull requests merged in 2020-12, with the labels that each got.

#1071 [feature] Improved support for STM32H7
  CMakeLists.txt
  doc/dev/developer.txt
  inc/backend.h
  inc/stlink.h
  inc/stm32.h
  src/common.c
  src/st-info/info.c
  src/st-util/gdb-server.c
  src/stlink-lib/chipid.c
  src/stlink-lib/chipid.h
  src/stlink-lib/flash_loader.c
  src/stlink-lib/helper.c
  src/stlink-lib/helper.h
  src/stlink-lib/reg.h
  src/stlink-lib/usb.c
  src/win32/sys_time.c
  src/win32/sys_time.h
Labels: code/feature-request, status/resolved, target/stm32h7

#1073 Fixed printf format string
  src/st-info/info.c
Labels: bug/fixed, status/resolved

#1074 Fixed gettimeofday for msvc
  src/win32/sys_time.c
  src/win32/sys_time.h
Labels: bug/fixed, os/windows, status/resolved

#1076 Bugfixes for compilation with clang
  src/stlink-lib/helper.c
Labels: bug/fixed, status/resolved

#1080 [feature] Included ITM functionality for building with MSVC
  CMakeLists.txt
  src/st-trace/trace.c
Labels: code/feature-request, os/windows, status/resolved

#1081 Correctly handle endianness without reference to host platform
  src/common.c
Labels: code/feedback, code/refactoring, status/resolved
