Repository stlink-org/stlink, pull requests merged in 2020-09, with the labels that each got.

#1027 Fixed reg_offset handling in stlink_usb_read_all_regs( )
  src/stlink-lib/usb.c
Labels: bug/fixed, component/st-util, dependency/libusb, status/resolved

#999 Add L5 support
  inc/stlink.h
  inc/stm32.h
  src/common.c
  src/stlink-lib/chipid.c
  src/stlink-lib/chipid.h
Labels: code/feature-request, needs/testing

#1035 [feature] Added support for STM32G031
  src/stlink-lib/chipid.c
Labels: code/feature-request, status/resolved

#1036 Merge branch 'connect_under_reset' into 'nightly'
  doc/dev/app-example/main.c
  src/common.c
  src/st-flash/flash.c
  src/st-info/info.c
  src/st-util/gdb-server.c
  src/stlink-gui/gui.c
  src/stlink-lib/usb.c
  src/stlink-lib/usb.h
  tests/usb.c
Labels: code/feature-request, status/resolved
