Repository stlink-org/stlink, pull requests merged in 2020-06, with the labels that each got.

#972 Fix installation path for desktop-file and icons.
  src/stlink-gui/CMakeLists.txt
Labels: code/feedback

#974 Fix for static linking of libssp
  CMakeLists.txt
Labels: bug/compilation, bug/fixed, os/freeBSD, os/linux, os/macOS, os/windows, status/resolved-verified

#986 Imported debian pkg-settings
  debian/.gitignore
  debian/changelog
  debian/control
  debian/copyright
  debian/gbp.conf
  debian/libstlink-dev.install
  debian/libstlink1.install
  debian/libstlink1.symbols
  debian/rules
  debian/source/format
  debian/source/options
  debian/stlink-gui.install
  debian/stlink-tools.install
  debian/stlink-tools.manpages
  debian/stlink.pc.in
  debian/watch
Labels: code/compatibility, general/documention, general/organisation, status/resolved

#983 [bugfix] Connect under reset for st-flash and st-util
  src/st-flash/flash.c
  src/st-util/gdb-server.c
Labels: bug/fixed, component/st-flash, component/st-util, needs/investigation, needs/testing

#987 [regression] Changed timeout on flash write
  src/stlink-lib/flash_loader.c
Labels: bug/fixed, bug/regression, component/stlink-lib, error/flash-loader, status/resolved

#989 st-flash: Fix for mmap() size_t overflow
  src/common.c
Labels: bug/fixed, component/st-flash, status/resolved

#993 Add support for FreeBSD's libusb reimplementation
  src/stlink-lib/logging.c
Labels: code/feedback, component/stlink-lib, dependency/libusb, os/freeBSD, status/resolved

#996 Merge branch develop
  CMakeLists.txt
  cmake/modules/get_version.cmake
  cmake/packaging/cpack_config.cmake
  inc/CMakeLists.txt
  src/common.c
  src/st-info/info.c
  src/stlink-lib/flash_loader.c
  src/stlink-lib/logging.c
Labels: status/resolved
