Repository stlink-org/stlink, pull requests merged in 2021-07, with the labels that each got.

#1159 [STM32H72X/3X]: Added full access to all device memory
  src/st-util/gdb-server.c
Labels: code/feature-request, code/feedback, component/st-util, status/resolved, status/resolved-verified, target/stm32h7

#1162 Fixed get_stm32l0_flash_base address for STM32L152RE
  src/common.c
Labels: bug/fixed, bug/regression, code/refactoring, component/stlink-lib, status/resolved, status/resolved-verified, target/stm32l0, target/stm32l1

#1167 Drop execute bits from source code files
  src/stlink-lib/md5.c
  src/stlink-lib/md5.h
Labels: code/compatibility, code/feedback, status/resolved
