Repository stlink-org/stlink, pull requests merged in 2021-05, with the labels that each got.

#1112 Support for writing option bytes on STM32F0/F1/F3
  flashloaders/stm32f0.s
  src/common.c
  src/stlink-lib/chipid.c
  src/stlink-lib/flash_loader.c
  src/stlink-lib/logging.c
Labels: code/feature-request, component/st-flash, status/resolved, status/resolved-verified, target/stm32f0, target/stm32f1, target/stm32f3

#1141 Added option byte info for STM32F411XX
  src/common.c
  src/st-util/gdb-server.c
  src/stlink-lib/chipid.c
  src/stlink-lib/chipid.h
  src/stlink-lib/flash_loader.c
Labels: code/feature-request, component/st-flash, status/resolved, target/stm32f4

#1142 cmake: Install shared libraries in proper directories.
  CMakeLists.txt
  src/win32/win32_socket.c
Labels: code/compatibility, code/feedback, status/resolved

#1144 Updated description of chip id 0x0457 to L01x/L02x
  src/stlink-lib/chipid.c
Labels: code/feedback, status/resolved, target/stm32l0

#1129 [refactoring] Moved chip-specific parameters into separate files
  src/stlink-lib/chipid.h
Labels: code/feature-request, code/feedback, code/refactoring, status/resolved
