Repository stlink-org/stlink, pull requests merged in 2021-03, with the labels that each got.

#1093 check format string for log messages
  src/common.c
  src/st-util/semihosting.c
  src/stlink-lib/logging.h
  src/stlink-lib/sg.c
  src/stlink-lib/usb.c
Labels: code/compatibility, code/feedback, code/refactoring, component/st-util, component/stlink-lib

#1085 Flash_loader: increase wait rounds for slow boards
  src/stlink-lib/flash_loader.c
Labels: code/feedback

#1102 option byte support improved
  src/st-flash/flash_opts.c
Labels: bug/fixed, status/resolved

#1103 [doc] Corrected spelling mistake in bug report template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: bug/fixed, general/documentation, status/resolved

#1104 Fixed support for STLINK/V1 programmer
  src/stlink-lib/usb.c
Labels: bug/fixed, bug/regression, component/st-flash, component/st-info, component/st-util, programmer/stlinkv1, status/resolved, target/stm32f1

#1106 Fixed old DFU serial number for STLINK programmers
  doc/man/st-info.1
  doc/man/st-info.md
  inc/stlink.h
  src/st-flash/flash.h
  src/st-flash/flash_opts.c
  src/st-info/info.c
  src/st-trace/trace.c
  src/st-util/gdb-server.c
  src/stlink-lib/usb.c
  src/stlink-lib/usb.h
Labels: bug/fixed, code/refactoring, component/st-info, component/st-util, programmer/stlinkv2, programmer/stlinkv2-1, programmer/stlinkv2-clone, status/resolved

#1101 Fixed STM32WB55 reading DEBUG IDCODE from the wrong address
  src/common.c
  src/stlink-lib/reg.h
Labels: bug/fixed, component/stlink-lib, status/resolved, target/stm32h7

#1109 GDB: Fixed problems with target description
  src/st-util/gdb-server.c
Labels: bug/fixed, component/st-util, status/resolved

#1107 [doc] Updated documentation on target resetting
  doc/man/st-flash.1
  doc/man/st-flash.md
  doc/tutorial.md
  src/st-flash/flash.c
Labels: general/documentation, status/resolved

#1110 Merge branch develop
  .github/ISSUE_TEMPLATE/bug-report.md
  .travis.yml
  CHANGELOG.md
  README.md
  contributors.txt
  doc/compiling.md
  doc/devices_boards.md
  doc/man/st-flash.1
  doc/man/st-flash.md
  doc/man/st-info.1
  doc/man/st-info.md
  doc/tutorial.md
  doc/version_support.md
  inc/stlink.h
  src/common.c
  src/st-flash/flash.c
  src/st-flash/flash.h
  src/st-flash/flash_opts.c
  src/st-info/info.c
  src/st-trace/trace.c
  src/st-util/gdb-server.c
  src/stlink-lib/reg.h
  src/stlink-lib/usb.c
  src/stlink-lib/usb.h
Labels: general/organisation, status/resolved

#1111 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: general/organisation, status/resolved

#1113 Flash loader rework
  flashloaders/Makefile
  flashloaders/cleanroom.md
  flashloaders/stm32f0.s
  flashloaders/stm32f4.s
  flashloaders/stm32f4lv.s
  flashloaders/stm32f7.s
  flashloaders/stm32f7lv.s
  flashloaders/stm32l0x.s
  flashloaders/stm32l4.s
  flashloaders/stm32lx.s
  src/common.c
  src/stlink-lib/flash_loader.c
  src/stlink-lib/reg.h
Labels: bug/fixed, bug/regression, component/st-flash, status/resolved, status/resolved-verified, target/stm32f0, target/stm32f1, target/stm32f4, target/stm32l0, target/stm32l4

#1114 [feature] Extended set of cmd line arguments for st-info and st-util
  doc/tutorial.md
  src/st-flash/flash.c
  src/st-flash/flash.h
  src/st-flash/flash_opts.c
  src/st-info/info.c
  src/st-util/gdb-server.c
  src/stlink-lib/helper.c
  src/stlink-lib/helper.h
  src/stlink-lib/usb.c
  src/stlink-lib/usb.h
Labels: code/feature-request, component/st-info, component/st-util, status/resolved

#1116 Removed abort() from stlink-lib
  src/common.c
Labels: code/refactoring, component/stlink-lib, status/resolved

#1119 Applied missing changes to tests
  tests/flash.c
Labels: bug/compilation, bug/fixed, code/compatibility, component/st-flash, status/resolved
