Repository stlink-org/stlink, pull requests merged in 2021-08, with the labels that each got.

#1166 Fixed segfault if chip was not found in chip config files
  src/stlink-lib/chipid.c
Labels: bug/fixed, bug/regression, code/refactoring, status/resolved

#1168 Use proper Markdown headers for supported MCUs
  doc/devices_boards.md
Labels: general/documentation, status/resolved

#1169 Fixed parsing hex numbers in chip config files
  inc/stlink.h
  src/stlink-lib/chipid.c
Labels: bug/fixed, component/stlink-lib, status/resolved

#1172 Corrected flash_pagesize to use hex format
  config/chips/F04x.chip
  config/chips/F07x.chip
  config/chips/F09x.chip
  config/chips/F0xx.chip
  config/chips/F0xx_small.chip
  config/chips/F1_XL-density.chip
  config/chips/F1_connectivity_line.chip
  config/chips/F1_high-density.chip
  config/chips/F1_low-density.chip
  config/chips/F1_medium-density.chip
  config/chips/F1_value_line.chip
  config/chips/F1_value_line_high-density.chip
  config/chips/F2.chip
  config/chips/F303_high_density.chip
  config/chips/F334_medium_density.chip
  config/chips/F37x.chip
  config/chips/F3xx_small.chip
  config/chips/F410.chip
  config/chips/F411xx.chip
  config/chips/F412.chip
  config/chips/F413.chip
  config/chips/F42x_F43x.chip
  config/chips/F446.chip
  config/chips/F46x_F47x.chip
  config/chips/F4xx.chip
  config/chips/F4xx_dynamic_efficiency.chip
  config/chips/F4xx_low_power.chip
  config/chips/F72x_F73x.chip
  config/chips/F76xxx.chip
  config/chips/F7xx.chip
  config/chips/G030_G031_G041.chip
  config/chips/G070_G071_G081.chip
  config/chips/G4_cat2.chip
  config/chips/G4_cat3.chip
  config/chips/H72x_H73x.chip
  config/chips/H74x_H75x.chip
  config/chips/H7Ax_H7Bx.chip
  config/chips/L011.chip
  config/chips/L0xx_cat2.chip
  config/chips/L0xx_cat5.chip
  config/chips/L152RE.chip
  config/chips/L1xx_cat2.chip
  config/chips/L1xx_high-density.chip
  config/chips/L1xx_medium-density.chip
  config/chips/L1xx_medium-plus-density.chip
  config/chips/L41x.chip
  config/chips/L43x_L44x.chip
  config/chips/L45x_L46x.chip
  config/chips/L496x_L4A6x.chip
  config/chips/L4Rx.chip
  config/chips/L4xx.chip
  config/chips/WB55.chip
  config/chips/unknown_device.chip
Labels: bug/regression, component/stlink-lib, status/resolved

#1173 Added support for STM32WLEx
  config/chips/WLE.chip
  src/stlink-lib/chipid.c
  src/stlink-lib/chipid.h
Labels: code/feature-request, component/stlink-lib, status/resolved, target/stm32wle

#1176 Fixed compilation for MSVC
  CMakeLists.txt
  src/common.c
  src/stlink-lib/chipid.c
Labels: bug/compilation, status/resolved, bug/fixed

#1178 Removed redundant array
  src/stlink-lib/chipid.c
Labels: code/refactoring, status/resolved

#1179 Fixed few warnings for msvc about type conversion with possible lost data
  src/common.c
  src/st-flash/flash.c
  src/st-util/gdb-server.c
  src/stlink-lib/flash_loader.c
Labels: component/st-util, component/st-flash, component/stlink-lib, status/resolved, bug/fixed
