Repository stlink-org/stlink, pull requests merged in 2022-12, with the labels that each got.

#1279 [compilation] Corrected path to stlink/chips subdirectory
  CMakeLists.txt
  README.md
Labels: os/macOS, bug/compilation, status/resolved, bug/fixed, status/resolved-verified, error/compilation, code/compatibility

#1281 Added udev-rule rule for the V3 MINIE programmer
  config/udev/rules.d/49-stlinkv3.rules
Labels: status/resolved, programmer/stlinkv3, code/feedback, code/compatibility

#1284 [compilation] Fixed GUI compilation failure on OpenBSD i386
  src/stlink-gui/gui.c
Labels: status/resolved, bug/fixed, os/freeBSD

#1288 [doc] Added device ID for GD32F303VET6
  doc/devices_boards.md
Labels: general/documentation, status/resolved, target/gd32f3
