Repository stlink-org/stlink, pull requests merged in 2022-08, with the labels that each got.

#1254 Added option byte address for L4Rx devices
  config/chips/L4Rx.chip
Labels: code/feature-request, component/stlink-lib, status/resolved, code/feedback

#1259 [doc] Added `make install` to the macOS compiling instructions
  doc/compiling.md
Labels: general/documentation, status/resolved, code/feedback

#1265 Fixed flash regs addr for STM32L152RET6 in common_flash.c
  src/common_flash.c
Labels: target/stm32l1, component/stlink-lib, status/resolved, bug/fixed, status/resolved-verified

#1266 Fixed flash, dbgmcu and rcc registers for STM32L1
  inc/stm32.h
  inc/stm32flash.h
  src/common.c
  src/common_flash.c
  src/flashloader.c
Labels: target/stm32l0, target/stm32l1, component/stlink-lib, status/resolved, bug/fixed, status/resolved-verified

#1267 Fix compilation with gcc-12
  cmake/modules/c_flags.cmake
Labels: os/linux, code/compilation-warning, status/resolved, status/resolved-verified, code/compatibility
