Repository stlink-org/stlink, pull requests merged in 2022-02, with the labels that each got.

#1220 [refactoring] sourcefile 'common.c'
  CHANGELOG.md
  inc/stm32.h
  inc/stm32flash.h
  src/common.c
  src/map_file.c
  src/map_file.h
  src/stlink-lib/chipid.h
Labels: needs/issuer-feedback, code/refactoring, component/stlink-lib

#1221 Set C standard through cmake variables
  CMakeLists.txt
  cmake/modules/c_flags.cmake
Labels: status/resolved, code/feedback, code/compatibility

#1227 Added writing and reading for STM32WL option bytes
  config/chips/WLx5.chip
  inc/stm32flash.h
  src/option_bytes.c
Labels: component/stlink-lib, status/resolved, target/stm32wl
