Repository stlink-org/stlink, pull requests merged in 2024-10, with the labels that each got.

#1426 Replaced deprecated cmd to fix package uninstall
  cmake_uninstall.cmake.in
Labels: os/windows, os/linux, status/resolved, bug/fixed, status/resolved-verified, code/compatibility

#1427 Fixed compilation error -Wshorten-64-to-32 in stlink-lib/usb.c
  src/stlink-lib/usb.c
Labels: component/stlink-lib, bug/compilation, status/resolved, bug/fixed, status/resolved-verified, code/compatibility

#1421 Make path to .chip files relative to installation directory on Windows
  .gitignore
  CMakeLists.txt
  src/stlink-lib/chipid.c
Labels: os/windows, dependency/libusb, bug/compilation, status/resolved, bug/fixed, code/feedback, status/resolved-verified

#1429 Fixed option parsing errors
  src/st-util/gdb-server.c
  src/stlink-lib/helper.c
Labels: component/st-util, component/stlink-lib, status/resolved, bug/fixed

#1422 Re-add support for STM32F411xC/xE option bytes read/write
  config/chips/F411xC_xE.chip
Labels: code/feature-request, bug/regression, target/stm32f4, component/stlink-lib, status/resolved, bug/fixed, code/feedback
